# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0002_alter_etsy_bulk_asset_image_upload_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etsyconnection',
            name='shop_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
