# Generated by Django 6.0.4 on 2026-04-14 17:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GelatoConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key_enc', models.TextField(blank=True)),
                ('store_id', models.CharField(blank=True, max_length=128)),
                ('store_name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gelato_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GelatoTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gelato_template_id', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=512)),
                ('preview_url', models.URLField(blank=True, max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='gelato_integration.gelatoconnection')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('connection', 'gelato_template_id')},
            },
        ),
        migrations.CreateModel(
            name='GelatoExportTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('design_image', models.ImageField(upload_to='gelato_exports/%Y/%m/')),
                ('title', models.CharField(blank=True, max_length=512)),
                ('description', models.TextField(blank=True)),
                ('tags', models.CharField(blank=True, max_length=1024)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16)),
                ('gelato_product_id', models.CharField(blank=True, max_length=255)),
                ('gelato_product_uid', models.CharField(blank=True, max_length=255)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gelato_export_tasks', to=settings.AUTH_USER_MODEL)),
                ('gelato_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='export_tasks', to='gelato_integration.gelatotemplate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
