# Generated by Django 6.0.4 on 2026-04-14 18:23

import gelato_integration.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelato_integration', '0002_temporarydesignupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporarydesignupload',
            name='image',
            field=models.ImageField(storage=gelato_integration.models._r2_storage, upload_to='temp_designs/'),
        ),
    ]
