# Generated by Django 6.0.4 on 2026-04-14 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelato_integration', '0003_alter_temporarydesignupload_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gelatoexporttask',
            name='artwork_r2_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name='gelatoexporttask',
            name='mockup_r2_url',
            field=models.URLField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name='gelatoexporttask',
            name='design_image',
            field=models.ImageField(blank=True, null=True, upload_to='gelato_exports/%Y/%m/'),
        ),
    ]
