# Generated by Django 6.0.4

import django.db.models.deletion
import gelato_integration.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gelato_integration", "0005_gelatoexporttask_free_shipping"),
    ]

    operations = [
        migrations.AddField(
            model_name="temporarydesignupload",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="gelato_temp_design_uploads",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="temporarydesignupload",
            name="image",
            field=models.ImageField(
                storage=gelato_integration.models._r2_storage,
                upload_to=gelato_integration.models.temp_design_upload_to,
            ),
        ),
    ]
