# Generated by Django 6.0.4 on 2026-04-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gelato_integration', '0007_ce_prefix_object_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gelatoconnection',
            name='store_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='gelatotemplate',
            name='gelato_template_id',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
