# Generated by Django 6.0.4 on 2026-04-15 07:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('gemini', 'Google Gemini')], default='gemini', max_length=32)),
                ('api_key_enc', models.TextField(blank=True)),
                ('model_name', models.CharField(choices=[('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite'), ('gemini-1.5-flash', 'Gemini 1.5 Flash'), ('gemini-1.5-pro', 'Gemini 1.5 Pro')], default='gemini-1.5-flash', max_length=64)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_connection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
