# Generated by Django 6.0.4 on 2026-04-15 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconnection',
            name='model_name',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.0-flash', 'Gemini 2.0 Flash'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite')], default='gemini-2.0-flash', max_length=64),
        ),
    ]
