# Generated by Django 6.0.4 on 2026-04-15 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0002_alter_aiconnection_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiconnection',
            name='model_name',
            field=models.CharField(choices=[('gemini-2.5-flash', 'Gemini 2.5 Flash'), ('gemini-2.5-pro', 'Gemini 2.5 Pro'), ('gemini-2.5-flash-lite', 'Gemini 2.5 Flash Lite'), ('gemini-2.0-flash-lite', 'Gemini 2.0 Flash Lite'), ('gemini-3-flash-preview', 'Gemini 3 Flash (Preview)'), ('gemini-3-pro-preview', 'Gemini 3 Pro (Preview)'), ('gemini-3.1-pro-preview', 'Gemini 3.1 Pro (Preview)')], default='gemini-2.5-flash', max_length=64),
        ),
    ]
