# Generated by Django 6.0.4 on 2026-04-15 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_integration', '0003_alter_aiconnection_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiconnection',
            name='use_grounding',
            field=models.BooleanField(default=False),
        ),
    ]
