# Generated by Django 6.0.4 on 2026-04-13 12:20

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('width', models.PositiveIntegerField()),
                ('height', models.PositiveIntegerField()),
                ('background_image', models.ImageField(upload_to='template_backgrounds/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'])])),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['template_set_id', 'order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateElement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('element_type', models.CharField(choices=[('placeholder', 'placeholder'), ('text', 'text'), ('rect', 'rect'), ('circle', 'circle'), ('triangle', 'triangle'), ('star', 'star'), ('hexagon', 'hexagon')], max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_rows', to='core.template')),
            ],
            options={
                'ordering': ['template_id', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='TemplateSet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='template_sets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='template',
            name='template_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='core.templateset'),
        ),
    ]
