# Generated by Django 6.0.4

import core.models
import core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_template_frame_shadow_sides_and_flags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="template",
            name="background_image",
            field=models.ImageField(
                storage=core.models.template_background_storage,
                upload_to="template_backgrounds/%Y/%m/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "webp"]
                    ),
                    core.validators.validate_real_image,
                ],
            ),
        ),
    ]
