# Generated by Django 6.0.4 on 2026-04-27 15:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_template_fold_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='fold_motif_shading_strength',
            field=models.FloatField(default=1.0, help_text='Gesamtstärke von Falten-Schatten und -Glanz im bedruckten Motiv (0–1); unabhängig vom Rahmen.', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='frame_inner_sides',
            field=models.PositiveSmallIntegerField(default=15, help_text='Innenschatten: Bit 1=oben,2=rechts,4=unten,8=links.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='frame_outer_sides',
            field=models.PositiveSmallIntegerField(default=15, help_text='Außenschatten: Bit 1=oben,2=rechts,4=unten,8=links.', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(15)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='frame_shadow_inner_enabled',
            field=models.BooleanField(default=False, help_text='Schatten/Tiefe ins Motiv (Seiten per Bitmaske).'),
        ),
        migrations.AlterField(
            model_name='template',
            name='frame_shadow_outer_enabled',
            field=models.BooleanField(default=False, help_text='Schatten nach außen am Rahmen (Seiten per Bitmaske).'),
        ),
    ]
