# Generated by Django 6.0.4 on 2026-04-27 15:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_template_fold_motif_shading_strength'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='template',
            name='fold_motif_shading_strength',
        ),
        migrations.AlterField(
            model_name='template',
            name='fold_highlight_strength',
            field=models.FloatField(default=0.08, help_text='Additive Glanzlichter an Faltenkämmen (0–1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='fold_shadow_depth',
            field=models.FloatField(default=0.2, help_text='Multiply-Blend-Stärke gegen Hintergrund-Luminanz (0–1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='fold_smoothing',
            field=models.PositiveSmallIntegerField(default=8, help_text='Pre-Smoothing-Radius (Pixel) der Heightmap vor Sobel.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(32)]),
        ),
        migrations.AlterField(
            model_name='template',
            name='fold_strength',
            field=models.FloatField(default=0.15, help_text='Verschiebungsstärke entlang der Sobel-Normalen (0–1).', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
    ]
